version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
      - "81:81" # For Nginx Proxy Manager UI
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:

